services:
  backend:
    image: loumfg/cender-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64

    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials
      - ./backend/alembic:/app/alembic

    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: loumfg/cender-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms: 
       - linux/amd64
       - linux/arm64
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    command: streamlit run app.py --server.address 0.0.0.0 --server.port 8501

  pytest:
    image: loumfg/cender-pytest
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials
    environment:
      - DATABASE_URL=sqlite:///./data/test.db
      - PYTHONUNBUFFERED=1
    command: pytest tests/ -v --tb=short
    profiles:
      - testing